# Generated by Django 4.2.3 on 2023-12-17 06:23

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="observations",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Select country of origin",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="observations",
            name="audio_file",
            field=models.FileField(
                upload_to="media/audio",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3", "wav"]
                    )
                ],
            ),
        ),
    ]
