# Generated by Django 4.2.3 on 2023-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_observations_country_alter_observations_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="observations",
            name="audio_duration",
            field=models.FloatField(
                blank=True, help_text="Duration of the audio in seconds", null=True
            ),
        ),
    ]
