# Generated by Django 4.2.3 on 2023-12-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_observations_audio_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="observations",
            name="audio_quality",
            field=models.CharField(
                choices=[
                    ("good", "Good quality recorder and clear sound of bird"),
                    (
                        "average",
                        "Average quality recorder and acceptable sound of bird",
                    ),
                    ("bad", "Bad recording device and hard to hear the sound of bird"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
