# Generated by Django 4.2.3 on 2023-12-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0004_observations_audio_quality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observations",
            name="audio_quality",
            field=models.IntegerField(
                choices=[
                    (1, "Good quality recorder and clear sound of bird"),
                    (2, "Average quality recorder and acceptable sound of bird"),
                    (3, "Bad recording device and hard to hear the sound of bird"),
                ],
                null=True,
            ),
        ),
    ]
