# Generated by Django 4.2.3 on 2023-12-24 06:13

import django.core.validators
from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0005_alter_observations_audio_quality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observations",
            name="audio_file",
            field=models.FileField(
                upload_to="media/audio",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3", "wav"]
                    ),
                    upload.models.validate_audio,
                ],
            ),
        ),
    ]
